Account/urls.py
from django.contrib.auth import views
from .views import myOwnLogin , signup, activate
from django.urls import path, re_path
from .views import (
                        TheHome,
                        MyCreateView,
                        MyUpdateView,
                        AuthorDeleteView,
                        ProfileView,
)
app_name = 'account'

urlpatterns = [
    path('', TheHome.as_view(), name='home' ),
    path('create', MyCreateView.as_view(), name='createArticle'),
    path('update/<int:pk>', MyUpdateView.as_view(), name='updateArticle'),
    path('delete/<int:pk>', AuthorDeleteView.as_view(), name='deleteArticle'),
    path('profile', ProfileView.as_view(), name='userProfile'),
    path('signup', signup, name='signup'),
]

food/urls.py
from django.urls import path
from .views import  DetDetailView, CategoryShow, base, AuthorShow

app_name = 'foodUrl'

urlpatterns = [
    path('',base.as_view() , name='home'),
    path('<slug:theSLUG>',DetDetailView.as_view(), name='detailView'),
    path('articles/<slug:categID>', CategoryShow.as_view(), name='categClass'),
    path('articles/users/<slug:username>', AuthorShow.as_view(), name='authClass')
]

stepByStep/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from Account.views import myOwnLogin, activate


urlpatterns = [
    path('login', myOwnLogin.as_view(), name='login'),
    path('',include('django.contrib.auth.urls')),
    path('admin' , admin.site.urls, name='admin'),
    path('', include('food.urls')),
    path('account/', include('Account.urls')),
    path('activate/<uidb64>/<token>/', activate, name='activate')
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/author_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
            <!-- Page Header-->
        <header class="masthead" style="background-image: url('{% static 'assets/img/home-bg.jpg' %}')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>Clean Blog</h1>
                            <span class="subheading">Articles that user had written</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
<!-- Main Content-->
    <h3 class="alert alert-primary text-center">Writer: {{ user.get_full_name }}</h3>
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
{#                # IMPORTANT ##}
                    {% for food in user.author.all %}
{#                        # IMPORTANT ##}
                    <!-- Post preview-->
                    <div class="post-preview">
                        <a href="{{ food.slug }}">
                            <h2 class="post-title">{{ food.name }}</h2>
                            <h3 class="post-subtitle">{{ food.desc | truncatewords:15 }}</h3>
                        </a>
                        <p class="post-meta">
                            Posted by
                           <a href="{% url 'foodUrl:authClass' food.user.username %}">{{ food.user.get_full_name }}</a>
                            on {{ food.date }}
                        </p>
                    </div>
                    <!-- Divider-->
                    <hr class="my-4" />
                    {% endfor %}
{#                    <!-- Pager-->#}
{#                    {% if foods.has_next %}#}
{#                    <div class="d-flex justify-content-end mb-4"><a class="btn btn-primary text-uppercase" href="{% url 'foodUrl:home' %}?page={{ foods.next_page_number }}">Next</a></div>#}
{#                    {% endif %}#}
{#                    {% if foods.has_previous %}#}
{#                    <div class="d-flex justify-content-end mb-4"><a class="btn btn-primary text-uppercase" href="{% url 'foodUrl:home' %}?page={{ foods.previous_page_number }}">Back</a></div>#}
{#                     {% endif %}#}
                </div>
            </div>
        </div>
 {% endblock %}

templates/base.html
{% load static %}
{% load base_tag %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Clean Blog - Start Bootstrap Theme</title>
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="" rel="stylesheet" type="text/css" />
        <link href="" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href='{% url 'account:home' %}'>{% showTime %}</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                {% profCateg %}
            </div>
        </nav>

       {% block content %}

        {% endblock %}
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2021</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>

templates/categ_tags.html
<div class="collapse navbar-collapse myfont" id="navbarResponsive">
    <ul class="navbar-nav ms-auto py-4 py-lg-0">
        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'foodUrl:home' %}">خانه</a></li>
        {% for cat in cat %}
        {% if cat.parent == None %}
            <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'foodUrl:categClass' cat.slug%}">{{ cat.name }}</a></li>
        {% endif %}
        {% endfor %}
    </ul>
</div>

templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
            <!-- Page Header-->
        <header class="masthead" style="background-image: url('{% static 'assets/img/home-bg.jpg' %}')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>Clean Blog</h1>
                            <span class="subheading">A Blog Theme by Start Bootstrap</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
<!-- Main Content-->
    <h3 class="alert alert-primary text-center myfont">food group: {{ catp.name }}</h3>
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
{#                # IMPORTANT ##}
                    {% for food in catp.categs.all %}
{#                        # IMPORTANT ##}
                    <!-- Post preview-->
                    <div class="post-preview">
                        <a href="{% url 'foodUrl:detailView' food.slug %}">
                            <h2 class="post-title">{{ food.name }}</h2>
                            <h3 class="post-subtitle">{{ food.desc | truncatewords:15 }}</h3>
                        </a>
                        <p class="post-meta">
                            Posted by
                            <a href="#!">{{ food.auth }}</a>
                            on {{ food.date }}
                        </p>
                    </div>
                    <!-- Divider-->
                    <hr class="my-4" />
                    {% endfor %}
{#                    <!-- Pager-->#}
{#                    {% if foods.has_next %}#}
{#                    <div class="d-flex justify-content-end mb-4"><a class="btn btn-primary text-uppercase" href="{% url 'foodUrl:home' %}?page={{ foods.next_page_number }}">Next</a></div>#}
{#                    {% endif %}#}
{#                    {% if foods.has_previous %}#}
{#                    <div class="d-flex justify-content-end mb-4"><a class="btn btn-primary text-uppercase" href="{% url 'foodUrl:home' %}?page={{ foods.previous_page_number }}">Back</a></div>#}
{#                     {% endif %}#}
                </div>
            </div>
        </div>
 {% endblock %}

templates/details.html
{% extends 'base.html' %}
{% block content %}
        <header class="masthead" style="background-image: url('{{ object.img.url }}')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>{{ object.name }}</h1>

                        </div>
                    </div>
                </div>
            </div>

        </header>
    <center>

    <div class="col-md-10 col-lg-8 col-xl-7">
        {% if object.special_article %}
        {% if request.user.is_superuser or request.user.is_special_user %}
        <span class="subheading">{{ object.desc|striptags }}</span>
        {% else %}
        <h3>{{ object.desc | truncatewords:30|safe }}</h3>
            <hr>
        <span class="subheading alert-warning">با عرض پوزش این محتوا برای اعضای ویژه تهیه شده است برای خرید اشتراک می‌تونید <a href="#">اقدام</a> کنید</span>
        {% endif %}
            {% else %}
            <span class="subheading">{{ object.desc|striptags }}</span>
        {% endif %}
    </div>
    </center>
{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% load static %}
{% block content %}
            <!-- Page Header-->
        <header class="masthead" style="background-image: url('{% static 'assets/img/home-bg.jpg' %}')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>Clean Blog</h1>
                            <span class="subheading">A Blog Theme by Start Bootstrap</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
<!-- Main Content-->
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    {% for food in foods %}
                    <!-- Post preview-->
                    <div class="post-preview">
                        <a href="{% url 'foodUrl:detailView' food.slug %}">
                            <h2 class="post-title">{{ food.name }}</h2>
                            <h3 class="post-subtitle">{{ food.desc | truncatewords:15|safe }}</h3>
                        </a>
                        <p class="post-meta">
                            Posted by
                            <a href="{% url 'foodUrl:authClass' food.user%}">{{ food.user.get_full_name }}</a>
                            on {{ food.date }}
                        </p>
                    </div>
                    <!-- Divider-->
                    <hr class="my-4" />
                    {% endfor %}
                    <!-- Pager-->
                    {% if page_obj.has_next %}
                    <div class="d-flex justify-content-end mb-4"><a class="btn btn-primary text-uppercase" href="{% url 'foodUrl:home' %}?page={{ page_obj.next_page_number }}">Next</a></div>
                    {% endif %}
                    {% if page_obj.has_previous %}
                    <div class="d-flex justify-content-end mb-4"><a class="btn btn-primary text-uppercase" href="{% url 'foodUrl:home' %}?page={{ page_obj.previous_page_number }}">Back</a></div>
                     {% endif %}
                </div>
            </div>
        </div>
 {% endblock %}